# Generated by Django 5.1 on 2025-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alphabet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="letterimage",
            old_name="path",
            new_name="letter_path",
        ),
        migrations.AddField(
            model_name="letterimage",
            name="object_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
