# Generated by Django 5.1 on 2025-03-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alphabet", "0002_rename_path_letterimage_letter_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letterimage",
            name="audio_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
