# Generated by Django 5.1 on 2025-03-17 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alphabet", "0004_testletters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letterimage",
            name="audio_path",
        ),
    ]
