# Generated by Django 5.1 on 2025-03-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alphabet", "0006_lettertimestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="HindiLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=10)),
                ("transliteration", models.CharField(max_length=20)),
                ("display_order", models.IntegerField()),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Stroke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroke_order", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("svg_path", models.TextField()),
                ("start_point_x", models.IntegerField()),
                ("start_point_y", models.IntegerField()),
                ("text_position_x", models.IntegerField()),
                ("text_position_y", models.IntegerField()),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strokes",
                        to="alphabet.hindiletter",
                    ),
                ),
            ],
            options={
                "ordering": ["letter", "stroke_order"],
            },
        ),
        migrations.CreateModel(
            name="KeyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point_order", models.IntegerField()),
                ("x_coordinate", models.IntegerField()),
                ("y_coordinate", models.IntegerField()),
                (
                    "stroke",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_points",
                        to="alphabet.stroke",
                    ),
                ),
            ],
            options={
                "ordering": ["stroke", "point_order"],
            },
        ),
    ]
